package org.elainehello.finance.builders;

import org.elainehello.finance.api.ReportBuilder;
import org.elainehello.finance.api.Transaction;

import java.util.List;
/*
*  A concrete builder that create a PDF version
*/
public class PdfReportBuilder extends ReportBuilder {

    @Override
    public void buildHeader(String companyName) {
        report.setFormat("PDF");
        report.addSection("[COMPANY]: " + companyName);
    }

    @Override
    public void buildContent(List<Transaction> data) {
        StringBuilder table = new StringBuilder("DATA | DESC | AMOUNT\n");
        for (Transaction t : data) {
            table.append(
                    String.format("%s | %s | %s\n", t.date(), t.description(), t.amount())
            );
        }
        report.addSection(table.toString());
    }

    @Override
    public void buildFooter() {
        report.addSection("Generated by FinanceService v1.0");
    }

}
