package org.elainehello.finance.app;

import org.elainehello.finance.api.ReportBuilder;
import org.elainehello.finance.api.Transaction;
import org.elainehello.finance.api.Report;
import org.elainehello.finance.builders.PdfReportBuilder;
import org.elainehello.finance.core.ReportDirector;

import java.util.Arrays;
import java.util.List;
import java.math.BigDecimal;
import java.time.LocalDate;

public class Main {
    public static void main(String[] args) {
        // 1. Mock Data (In reality this comes from a Database)
        List<Transaction> data = Arrays.asList(
                new Transaction(LocalDate.now(), "Cloud Server Fee", new BigDecimal("150.00")),
                new Transaction(LocalDate.now(), "License Renewal", new BigDecimal("49.99"))
        );

        // 2. Setup Pattern
        ReportDirector director = new ReportDirector();
        ReportBuilder builder = new PdfReportBuilder();

        // 3. Construct and Run
        Report finalReport = director.construct(builder, "TechCorp LLC", data);
        finalReport.display();
    }
    /*
    * output stdout
    *   ---Generating PDF Report---
        [COMPANY]: TechCorp LLC
        DATA | DESC | AMOUNT
        2025-12-24 | Cloud Server Fee | 150.00
        2025-12-24 | License Renewal | 49.99

        Generated by FinanceService v1.0
        --------------------------------------
    * */
}